- name: Start fhirbase amazon ec2
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-8c68b739'
    region: us-west-1
  tasks:
    - name: Start fhirbase performance test amazon ec2 instance
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: subnet-77f6152e
      register: ec2
    - name: Wait for SSH to come up on fhirbase performance test amazon ec2 instance
      wait_for: host={{ item.public_dns_name }}
                port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
